# Generated by Django 5.2.7 on 2025-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('lapangan', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
    ]
