# Generated by Django 5.2.7 on 2025-10-24 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lapangan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='New Ad!', max_length=100)),
                ('deskripsi', models.TextField(default='Click to see details..')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='iklan_banners/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iklans', to=settings.AUTH_USER_MODEL)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iklans', to='lapangan.lapangan')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
