# Generated by Django 5.2.7 on 2025-10-22 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklan',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iklans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iklan',
            name='lapangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iklans', to='lapangan.lapangan'),
        ),
    ]
