# Generated by Django 5.2.5 on 2025-10-22 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_iklan_host_alter_iklan_lapangan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iklan',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='iklan',
            name='banner',
            field=models.ImageField(upload_to='iklan_banners/'),
        ),
        migrations.AlterField(
            model_name='iklan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
