# Generated by Django 5.2.7 on 2025-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_iklan_options_alter_iklan_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iklan',
            name='deskripsi',
            field=models.TextField(default='Click to see details..'),
        ),
        migrations.AddField(
            model_name='iklan',
            name='judul',
            field=models.CharField(default='New Ad!', max_length=100),
        ),
        migrations.AlterField(
            model_name='iklan',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='iklan_banners/'),
        ),
    ]
