# Generated by Django 5.2.5 on 2025-10-24 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id_lapangan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('voli', 'Voli'), ('lainnya', 'Lainnya')], max_length=50)),
                ('lokasi', models.CharField(max_length=200)),
                ('harga_per_jam', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('jam_buka', models.TimeField()),
                ('jam_tutup', models.TimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lapangans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
