# Generated by Django 5.2.7 on 2025-10-10 09:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id_lapangan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('futsal', 'Futsal'), ('basket', 'Basket'), ('badminton', 'Badminton'), ('tenis', 'Tenis'), ('voli', 'Voli'), ('lainnya', 'Lainnya')], max_length=50)),
                ('lokasi', models.CharField(max_length=200)),
                ('harga_per_jam', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('foto', models.ImageField(upload_to='static/img/')),
                ('jam_buka', models.TimeField()),
                ('jam_tutup', models.TimeField()),
            ],
        ),
    ]
