# Generated by Django 5.2.7 on 2025-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0002_lapangan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
